### ISSUE TITLE
Glitch Hosting

### ISSUE THREAD

**Issue by AndyIsCool5463** [longshotdev/rice-bot#15]
Make sure to include following files.

package.json
`
"engines": {
    "node": "12.x"
  }
`

and a watch.json
```{
  "install": {
    "include": [
      "^package\\.json$",
      "^\\.env$"
    ]
  },
  "restart": {
    "exclude": [
      "^public/",
      "^dist/"
    ],
    "include": [
      "\\.js$",
      "\\.json"
    ]
  },
  "throttle": 900000
}
```

eat my shit bitch.

**Comment by invisicat** [comment]
Glitch hosting is not an option anymore, consider different options, also update package.json to
`"engines": { "node": "14.x" }

`

**Comment by invisicat** [comment]
Got a hosting option, closing.
